version: '3'

networks:
    lolapi:
        driver: bridge                  # Needed to get around a bug at connection
services:
    loldb:
        image: 'mysql:8'
        environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWD}
        - MYSQL_DATABASE=${MYSQL_DB}
        networks:
            - lolapi
        ports:
        - '3306:3306'
    redisdb:
        image: 'redis:7'
        networks:
            - lolapi
        ports:
        - '6379:6379'
    lolmongo:
        image: mongo
        networks:
            - lolapi
        ports:
          - "27017:27017"
        environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWD}
